services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: notif
      POSTGRES_PASSWORD: notif
      POSTGRES_DB: notif
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notif -d notif"]
      interval: 3s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 5

  integrations-mock:
    build:
      context: .
      dockerfile: Dockerfile.integrations-mock
    ports:
      - "8099:8099"

  app:
    build: .
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      integrations-mock:
        condition: service_started
    environment:
      DATABASE_URL: postgres://notif:notif@postgres:5432/notif?sslmode=disable
      REDIS_ADDR: redis:6379
      CHAMADOS_API_BASE_URL: http://integrations-mock:8099
      MAPAS_API_BASE_URL: http://integrations-mock:8099/mapas
      PUSH_MOCK_URL: http://integrations-mock:8099/v1/push/send
    ports:
      - "8080:8080"

volumes:
  pgdata:
